#!/usr/bin/python
# See README for copyright and licensing details.

import sys

from testtools.tests import test_suite
from testtools import TextTestResult

result = TextTestResult(sys.stdout)
result.startTestRun()
try:
    test_suite().run(result)
finally:
    result.stopTestRun()
